Fix failed to build from source on Linux due to the usage for backslashes(preprocessor directives)
Currently cross-building on Linux will fail during compilation stage
with the following error message:

```
[ 13%] Building CXX object CMakeFiles/wkbre.dir/gameset/loadgameset.cpp.obj
wkbre/gameset/loadgameset.cpp:17:10: fatal error: ..\global.h: No such file or directory
   17 | #include "..\global.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/wkbre.dir/build.make:594: CMakeFiles/wkbre.dir/gameset/loadgameset.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:100: CMakeFiles/wkbre.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

This is due to the backslash usage in the #include pre-processor
directives which is not compatible in Unix operating systems.  This
patch fixes the problem by replacing them with forward slashes which
should be compatible with both Windows and Linux platforms.

Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>