Fix failed to build from source on Linux due to filename case insensitivity(OpenGL headers)
Currently cross-building on Linux will fail during compilation stage
with the following error message:

```
[ 16%] Building CXX object CMakeFiles/wkbre.dir/wkbre.cpp.obj
wkbre/renderer_ogl1.cpp:18:10: fatal error: gl/gl.h: No such file or directory
   18 | #include <gl/gl.h>
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/wkbre.dir/build.make:314: CMakeFiles/wkbre.dir/renderer_ogl1.cpp.obj] Error 1
```

This is due to the filename casing of the OpenGL header files which
is not accessible in the case-sensitive file/operating systems like
GNU/Linux.

This patch fixes the problem by using the upper-case GL header directory
as it seems to be the proper filename casing of the OpenGL headers.

Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>